"""Interface definitions for the orchestrator subsystem.

This module provides the structured result and context types shared by the
PRE_MARKET_FULL_SCAN orchestrator implementation and its module stubs.  The contracts
mirror the Result[T] workflow conventions established in ``common.interface``
while remaining lightweight enough for downstream orchestrators to reuse.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

import msgspec

from common.interface import BoundLogger, EventBus, ResultStatus
from journal.interface import OperatingMode, RunType

__all__ = ["RunSummary", "ModuleResult", "OrchestratorContext"]


class RunSummary(msgspec.Struct, kw_only=True, frozen=True):
    """Aggregate metrics describing a completed orchestrator run.

    Attributes:
        candidates_count: Total number of scanner candidates generated by the run.
        execution_reports_count: Total number of execution reports produced by the run.
        failures: Count of modules that failed irrecoverably.
        status: Aggregate :class:`ResultStatus` for the run.
        duration_ms: Total runtime in milliseconds measured from orchestrator
            start to completion (inclusive of persistence).
    """

    candidates_count: int
    failures: int
    status: ResultStatus
    duration_ms: int
    execution_reports_count: int = 0


class ModuleResult(msgspec.Struct, kw_only=True, frozen=True):
    """Structured outcome for an individual module execution."""

    module_name: str
    status: ResultStatus
    output_data: Any | None = None
    error: BaseException | None = None


@dataclass(slots=True, frozen=True)
class OrchestratorContext:
    """Immutable context shared with orchestrator modules during execution."""

    run_id: str
    run_type: RunType
    mode: OperatingMode
    config: Mapping[str, Any]
    logger: BoundLogger
    event_bus: EventBus

    @property
    def config_map(self) -> Mapping[str, Any]:
        return self.config
